### ISSUE TITLE
Coonamessett Annotation

### ISSUE THREAD

**Issue by aus10powell** [aus10powell/MIT-Fishery-Counter#4]
# Create Golden Standard Dataset for Coonamessett Fishery Site

## Background
We need to establish a golden standard dataset for the Coonamessett fishery site using data from the 2024 season. This dataset will reflect the current camera conditions and latest model training methods, serving as a benchmark for future models.

## Objective
Create a high-quality, manually annotated dataset from the 2024 season videos, focusing on scenes with multiple fish to address label imbalance issues.

## Requirements
1. Use video file: `1_2024-05-14_09-00-00_987`
2. Create a spreadsheet with the following columns:
   - "Minute": The minute mark since the video started
   - "Count": Number of fish that have passed the mid-point of the screen within the minute window

### Example Spreadsheet Format:

| Minute | Count |
|--------|-------|
| 1      | 0     |
| 2      | 0     |
| 3      | 0     |
| 4      | 0     |
| 5      | 0     |
| 6      | 25    |

Note: This example shows a sudden increase in fish count at minute 6, which is a good representation of the label imbalance issue we're addressing.

## Process
1. Download the video file from Dropbox
2. Use a video player to carefully review the footage
3. Count fish passing the mid-point of the screen for each minute
4. Record counts in the spreadsheet following the format shown above

## Reference
For comparison, the video file `2_2018-05-10_06-39-30` from the IRWA dataset contains 4 fish in a much shorter duration.

## Potential Challenges
- Accurate counting may be difficult when fish are swimming quickly or overlapping in multiple frames
- Maintaining focus during long periods without fish activity
- Handling sudden spikes in fish count, as seen in the example (0 to 25)

## Deliverables
1. Completed spreadsheet with minute-by-minute fish counts for the entire video duration
2. Brief report on the annotation process, including any challenges encountered or observations made

## Additional Notes
- Ensure consistent counting methodology throughout the video
- If possible, have multiple team members validate the counts to ensure accuracy
- Pay special attention to minutes with high fish counts to ensure accuracy

Please comment on this issue if you need any clarifications or have suggestions for improving the annotation process.

**Comment by TalhaNadeem001** [comment]
Hi aus10powell

I hope you're doing well. I was reviewing your project and noticed that I am unable to locate the video file named 1_2024-05-14_09-00-00_987 in your Dropbox. Could you please check if the file has been uploaded correctly or provide an alternative link if available?

Thanks in advance

**Comment by aus10powell** [comment]
Hi Talha,

Thank you for checking. Are you a part of MIT? This file is currently a student effort so would have to check if you are not

**Comment by TalhaNadeem001** [comment]
I apologize for the oversight. The project caught my attention, and I was eager to learn more about it

**Comment by aus10powell** [comment]
@TalhaNadeem001 not a problem. Not obvious from README. I can check with the group and see if videos are available for open-source community

**Comment by Zhongqi-Chen** [comment]
40 video clips were chosen based on the 2024 stream-side count data, 30 have been counted by two volunteer counters. 
Each video is 10-min. 
Example format:

| Time      | Frame      | Species  | Direction |
|   :---:   |   :---:   |   :---:   |   :---: |
| 00:07:54  | 7108     | Herring    |    up |
| 00:07:55  | 7119     | Herring    |    down|
